### ISSUE TITLE
possible collaboration?

### ISSUE THREAD

**Issue by atherdon** [pavkout/react-mailkit#10]
Hi Pavlos, nice to meet you!
And hello from Ukraine ))

I find your repository a few months ago while serving GitHub.
Me and my friends working on a similar project. While we not using mjml yet - one of our goals is to build reusable react components for building email templates. 

Are you interested to collaborate at some point in the future?

Thanks,
Arthur

**Comment by pavkout** [comment]
Hi @atherdon, nice to meet you too, hey Ukraine. 

Sure, If I can help you I will do it.

Thanks,
Pavlos
